[build]
  functions = "out_functions"
  publish = "out_publish"
  command = "sed -i s/API_KEY_PLACEHOLDER/$API_KEY/g netlify.toml && yarn build"

[dev]
  functions = "out_functions"
  publish = "out_publish"
  framework = "#static"
